#! /bin/sh

sxhkd &
feh --bg-fill ~/Downloads/anita-jeanine-photography-nSqVAHyLb3o-unsplash.jpg &

~/.config/polybar/polybar.sh

killall compton
compton --dbus &

# Maps esc to capslock
xmodmap ~/.speedswapper &

bspc monitor -d I II III IV

killall mpd
mpd &

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config border_width 2
bspc config window_gap 20
bspc config top_padding 60

bspc config left_padding 30
bspc config right_padding 30
bspc config border_radius 15

#get xrdb colors
highlight=$(xrdb -query | grep "*.highlight" | cut -f 2)
background=$(xrdb -query | grep "*.background-no-transparancy:" | cut -f 2)

bspc config focused_border_color "#d8dee8"
bspc config normal_border_color "#2f343f"
bspc config presel_feedback_color "#ff5c57"

bspc config focus_follows_pointer true
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false

